services:
  - type: web
    name: voce-to-description-backend
    runtime: python
    plan: free
    branch: new-main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GROQ_API_KEY
        sync: false
    autoDeploy: true
